In [1]:
# Implementing KSOM For Iris Dataset

import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv("C:\Users\HP\Documents\LAB\DL\ex-4\heart.csv")
df

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3783711819.py, line 1)

In [3]:
x = df.iloc[:,:-1]
x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
2         0   0     3  
3         2   1     3  
4         1   3     2  
...     ...  ..   ...  
1020      2   0     2  
1021      1   1     3  
1022      1   1     2  
1023      2   0     2  
1024      1   1     3  

[1025 rows x 13 columns]

In [4]:
y = df.iloc[:,-1]
y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [5]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
x = scaler.fit_transform(x)

In [6]:
class KSOM(nn.Module):

    def __init__(self, input_dim, output_dim):
        super(KSOM, self).__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.weights = torch.randn(input_dim,output_dim)

    def forward(self, x):
        distances = torch.sum((x - self.weights)**2, axis=1)
        winner = torch.argmin(distances)
        return winner
    
    def weight_updation(self, x, winner, lr=0.02):
        d = x
        for i in range(self.output_dim):
            if i == winner:
                self.weights[i] += lr * d[i]
            return self.weights[i]

In [9]:
model = KSOM(input_dim=13, output_dim=13)

for epoch in range(2):
    for o in x:
        o = torch.Tensor(o)
        winner = model(o)
        print(model.weight_updation(o, winner, lr=0.2))

tensor([ 1.5189,  1.4252, -0.2078,  0.3496, -0.6410,  0.5848,  0.0475, -0.3707,
        -0.6981,  0.0953,  0.5840, -1.9132, -1.9259])
tensor([ 1.5189,  1.4252, -0.2078,  0.3496, -0.6410,  0.5848,  0.0475, -0.3707,
        -0.6981,  0.0953,  0.5840, -1.9132, -1.9259])
tensor([ 1.5189,  1.4252, -0.2078,  0.3496, -0.6410,  0.5848,  0.0475, -0.3707,
        -0.6981,  0.0953,  0.5840, -1.9132, -1.9259])
tensor([ 1.5189,  1.4252, -0.2078,  0.3496, -0.6410,  0.5848,  0.0475, -0.3707,
        -0.6981,  0.0953,  0.5840, -1.9132, -1.9259])
tensor([ 1.5189,  1.4252, -0.2078,  0.3496, -0.6410,  0.5848,  0.0475, -0.3707,
        -0.6981,  0.0953,  0.5840, -1.9132, -1.9259])
tensor([ 1.5189,  1.4252, -0.2078,  0.3496, -0.6410,  0.5848,  0.0475, -0.3707,
        -0.6981,  0.0953,  0.5840, -1.9132, -1.9259])
tensor([ 1.5189,  1.4252, -0.2078,  0.3496, -0.6410,  0.5848,  0.0475, -0.3707,
        -0.6981,  0.0953,  0.5840, -1.9132, -1.9259])
tensor([ 1.5189,  1.4252, -0.2078,  0.3496, -0.6410,  0.5848, 