In [1]:
import torch
from torch.autograd import Variable

In [2]:
a = Variable(torch.Tensor([[1,2],[3,4]]), requires_grad=True)
print(a)


tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [6]:
y = torch.sum(2*a**3)
print(y)

tensor(200., grad_fn=<SumBackward0>)


In [7]:
z = y.backward()
print(z)

None


In [5]:
print(a.grad)


tensor([[ 6., 24.],
        [54., 96.]])
tensor([[ 6., 24.],
        [54., 96.]])
