In [1]:
import torch
gpu = torch.cuda.is_available()
print(gpu)

False


In [2]:
#Creating_Tensor
a = torch.tensor([1,2,3], dtype = torch.float64)
print(a)
b = torch.tensor([4,5,6], dtype = torch.float64)
print(b)

tensor([1., 2., 3.], dtype=torch.float64)
tensor([4., 5., 6.], dtype=torch.float64)


In [3]:
#Addition
print(a+b)
print(torch.add(a,b))
print(a.add(b))

tensor([5., 7., 9.], dtype=torch.float64)
tensor([5., 7., 9.], dtype=torch.float64)
tensor([5., 7., 9.], dtype=torch.float64)


In [4]:
#Inplace_Addition
a.add_(7)

tensor([ 8.,  9., 10.], dtype=torch.float64)

In [5]:
#Multiplication
print(a*b)
print(a.mul(b))

tensor([32., 45., 60.], dtype=torch.float64)
tensor([32., 45., 60.], dtype=torch.float64)


In [6]:
#MatrixMultiplication
print(a.matmul(b))

tensor(137., dtype=torch.float64)


In [7]:
torch.add(a,b).sum()

tensor(42., dtype=torch.float64)

In [8]:
#DotMultiplication
a.dot(b)

tensor(137., dtype=torch.float64)

In [9]:
z = torch.zeros(2,3,dtype=int)
print(z)
o = torch.ones(2,3,dtype=int)
print(o)

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])


In [10]:
k = torch.tensor([1,2,3,4,5,6])
print("Tensor: ",k)
print("DataType: ",k.dtype)
print("Size: ",k.size())
print("Dimension: ",k.dim())

Tensor:  tensor([1, 2, 3, 4, 5, 6])
DataType:  torch.int64
Size:  torch.Size([6])
Dimension:  1


In [11]:
print(k[0])
print(k[4])
print(k[0:3])

tensor(1)
tensor(5)
tensor([1, 2, 3])


In [12]:
#Sort
arr = torch.tensor([10,4,3,6,2,1,7,9])
print("Ascending: ",torch.sort(arr))
print("Descending: ",torch.sort(arr, descending=True))

Ascending:  torch.return_types.sort(
values=tensor([ 1,  2,  3,  4,  6,  7,  9, 10]),
indices=tensor([5, 4, 2, 1, 3, 6, 7, 0]))
Descending:  torch.return_types.sort(
values=tensor([10,  9,  7,  6,  4,  3,  2,  1]),
indices=tensor([0, 7, 6, 3, 1, 2, 4, 5]))


In [13]:
#Changing_View_of_Tensor
m = torch.arange(0,9)
n = m.view(3,3)
print(m)
print(n)
o = torch.arange(8)
p = o.view(2,2,2)
print(o)
print(p)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
