In [1]:
import torch

In [2]:
a=[[2,1,4],[2,1,2],[3,4,3]]
a=torch.tensor(a,dtype=torch.int)
a

tensor([[2, 1, 4],
        [2, 1, 2],
        [3, 4, 3]], dtype=torch.int32)

In [3]:
b=[[1,2,3],[4,5,6],[7,8,9]]
b=torch.tensor(b,dtype=torch.int)
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [4]:
r=[[0,0,0],[0,0,0],[0,0,0]]
r=torch.tensor(r,dtype=torch.int)
r

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [5]:
for i in range(len(a)):
    for j in range (len(b[0])):
        for k in range (len(b)):
            r[i][j]+= a[i][k]*b[k][j]

In [6]:
r

tensor([[34, 41, 48],
        [20, 25, 30],
        [40, 50, 60]], dtype=torch.int32)

inverse of matrix

In [7]:
A=[[1,0,1],[0,1,1],[1,1,1]]
A=torch.tensor(A,dtype=torch.int)
A

tensor([[1, 0, 1],
        [0, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [8]:
f,h=A.shape
f

3

In [9]:
import numpy as np

In [10]:
I = np.identity(n=f)
I=torch.tensor(I,dtype=torch.int)
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.int32)

In [11]:
M = np.concatenate((A,I),axis=1)
M=torch.tensor(M,dtype=torch.int)
M

tensor([[1, 0, 1, 1, 0, 0],
        [0, 1, 1, 0, 1, 0],
        [1, 1, 1, 0, 0, 1]], dtype=torch.int32)

In [12]:
for i in range (0,f):
    pivot = M[i][i]
    row =M[i]
    M[i] = row / pivot
    for j in [k for k in range(0,f) if k!=i]:
        M[j] = M[j]-M[i]*M[j][i]
    inverse = M[:,f:]

In [13]:
inverse

tensor([[ 0, -1,  1],
        [-1,  0,  1],
        [ 1,  1, -1]], dtype=torch.int32)