In [1]:
import torch

In [12]:
a=[[3,1,4],[2,1,2],[2,4,1]]
a=torch.tensor(a,dtype=torch.int) #multi-dimensional matrix containing elements of a single data type
a

tensor([[3, 1, 4],
        [2, 1, 2],
        [2, 4, 1]], dtype=torch.int32)

In [13]:
b=[[3,2,3],[3,5,6],[7,8,5]]
b=torch.tensor(b,dtype=torch.int)
b

tensor([[3, 2, 3],
        [3, 5, 6],
        [7, 8, 5]], dtype=torch.int32)

In [14]:
r=[[0,0,0],[0,0,0],[0,0,0]]
r=torch.tensor(r,dtype=torch.int)
r

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [15]:
for i in range(len(a)):
    for j in range (len(b[0])):
        for k in range (len(b)):
            r[i][j]+= a[i][k]*b[k][j]

In [16]:
r

tensor([[40, 43, 35],
        [23, 25, 22],
        [25, 32, 35]], dtype=torch.int32)

inverse of matrix

In [7]:
A=[[1,0,1],[0,1,1],[1,1,1]]
A=torch.tensor(A,dtype=torch.int)
A
f,h=A.shape
f

3

In [8]:
import numpy as np
I = np.identity(n=f)
I=torch.tensor(I,dtype=torch.int)
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.int32)

In [9]:
M = np.concatenate((A,I),axis=1)
M=torch.tensor(M,dtype=torch.int)
M

tensor([[1, 0, 1, 1, 0, 0],
        [0, 1, 1, 0, 1, 0],
        [1, 1, 1, 0, 0, 1]], dtype=torch.int32)

In [10]:
for i in range (0,f):
    pivot = M[i][i]
    row =M[i]
    M[i] = row / pivot
    for j in [k for k in range(0,f) if k!=i]:
        M[j] = M[j]-M[i]*M[j][i]
    inverse = M[:,f:]

In [11]:
inverse

tensor([[ 0, -1,  1],
        [-1,  0,  1],
        [ 1,  1, -1]], dtype=torch.int32)